# helper file for stikine inseason management

# load ----
library(extrafont)
library(reshape)
library(reshape2)
library(stringr)
library(lubridate)
library(ISOweek)
library(ggplot2)
library(dplyr)
library(dynlm)
library(psych)
library(stats)
library(ggplot2)
library(ggfortify)
library(plyr)
library(reshape2)
library(lattice)
library(latticeExtra)
library(gridExtra)
library(ggplot2)
library(MASS)
library(survival)
library(scatterplot3d)
library(vcd)
library(grid)
library(calibrate)
library(scales)
library(extrafont)
library(RColorBrewer)
library(pwr)
library(fitdistrplus)
library(mixtools)
library(doBy)
library(Hmisc)
library(mixdist)
loadfonts(device="win")
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_bw(base_size=12, base_family='Times New Roman') +
          theme(panel.grid.major = element_blank(), 
                panel.grid.minor = element_blank(), plot.title = element_text(hjust = 0.5)))
